# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterHybridiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlutterHybridiOS

  target 'FlutterHybridiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterHybridiOSUITests' do
    # Pods for testing
  end

end
